nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    "^/api/v1/":
      allow_origin: ["http://18.204.212.123", "http://localhost:8080"]
      allow_headers:
        [
          "X-API-KEY",
          "Origin",
          "X-Requested-With",
          "Content-Type",
          "Accept",
          "Access-Control-Request-Method",
          "Authorization",
        ]
      allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
      max_age: 3600
